/*============================================================================*/
/*  Copyright (C) 2009-2015, iSOFT INFRASTRUCTURE SOFTWARE CO.,LTD.
 *
 *  All rights reserved. This software is iSOFT property. Duplication
 *  or disclosure without iSOFT written authorization is prohibited.
 *
 *  @file       <PduR_Cfg.h>
 *  @brief      <>
 *
 *  <MCU:	>
 *
 *  @author     <>
 *  @date       <2015-04-01 15:26:08>
 */
/*============================================================================*/


#ifndef  PDUR_CFG_H
#define  PDUR_CFG_H

/*=======[V E R S I O N  I N F O R M A T I O N]===============================*/
#define PDUR_CFG_H_AR_MAJOR_VERSION  2
#define PDUR_CFG_H_AR_MINOR_VERSION  3
#define PDUR_CFG_H_AR_PATCH_VERSION  0
#define PDUR_CFG_H_SW_MAJOR_VERSION  1
#define PDUR_CFG_H_SW_MINOR_VERSION  0
#define PDUR_CFG_H_SW_PATCH_VERSION  0

/*=======[I N C L U D E S]====================================================*/


/*=======[M A C R O S]========================================================*/
/* Config PDUR Module Variant */
#define PDUR_VARIANT_PC             VARIANT_PRE_COMPILE
#define PDUR_VARIANT_PB             VARIANT_POST_BUILD
#define PDUR_VARIANT_CFG            PDUR_VARIANT_PC   /* Variant Config */

/* Config Use DET or Not, Generated by Tool */
#define PDUR_DEV_ERROR_DETECT           STD_ON

/* Config Use DEM or Not, Generated by Tool */
#define PDUR_DEM_ERROR_DETECT			STD_OFF

/* Config get Com_VersionInfo or not */
#define PDUR_VERSION_INFO_API           STD_ON

/* Zero cost operation only support Loif and Com module */
#define PDUR_ZERO_COST_OPERATION        STD_OFF

/* Configuration PDU Router support for LINIF */
#define PDUR_LINIF_SUPPORT             	STD_OFF

/* Configuration PDU Router support for CANIF */
#define PDUR_CANIF_SUPPORT              STD_ON

/* Configuration PDU Router support for IPDUM */
#define PDUR_IPDUM_SUPPORT              STD_OFF

/* Configuration PDU Router support for COM  */
/* if PDUR_COM_SUPPORT= STD_ON, PDUR_CANIF_SUPPORT or PDUR_LINIF_SUPPORT must be STD_ON  */
#define PDUR_COM_SUPPORT              	STD_OFF

/* Configuration PDU Router support for CANTP  */
#define PDUR_CANTP_SUPPORT              STD_ON

/* Configuration PDU Router support for LINTP */
#define PDUR_LINTP_SUPPORT             	STD_OFF

/* Configuration PDU Router support for DCM */
#define PDUR_DCM_SUPPORT              	STD_ON

/* CAN_IF LIN_IF PDUR_ZERO_COST_OPERATION==STD_ON */
/* if PDUR_LINIF_SUPPORT=STD_ON this parameter has to be LIN_IF */
#define PDUR_SINGLE_IF					CAN_IF

/* CAN_TP LIN_TP */
#define PDUR_SINGLE_TP					CAN_TP

/* if PDUR_ZERO_COST_OPERATION = STD_ON this parameter has to be STD_OFF  */
#define PDUR_GATEWAY_OPERATION          STD_ON

/* if PDUR_GATEWAY_OPERATION = STD_ON this parameter has to be STD_OFF */
#define PDUR_MULTICAST_FROMIF_SUPPORT   STD_OFF

/* if PDUR_GATEWAY_OPERATION = STD_OFF this parameter has to be STD_OFF */
#define PDUR_FIFO_TX_BUFFER_SUPPORT     STD_ON

#define PDUR_MEMORY_SIZE              	100

#define PDUR_MAX_COMDESTTXPDU_NUMBER	10

#define PDUR_MAX_IFCONFPDU_NUMBER		10

#define PDUR_MAX_IFSRCRXPDU_NUMBER		5

#define PDUR_MAX_IFDESTRXPDU_NUMBER		10

#define PDUR_MAX_IPDUMRXPDU_NUMBER		10

#define PDUR_MAX_GWDESTTXPDU_NUMBER		10

/* if PDUR_VARIANT_PC time Generated */
#define PDUR_GETCONFIGURATION_ID                    0

/* if PDUR_VARIANT_PB time Generated */
#define PDUR_MAX_PBCONFIG_NUMBER		1

/* unchanged */
#define PDUR_MAX_BUSTYPE_NUMBER			3

#endif  /* end of PDUR_CFG_H */

/*=======[E N D   O F   F I L E]==============================================*/

