/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AC_CP_IOC.h
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : Capture
**     Version   : Component 02.212, Driver 01.19, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/3/23, 21:47
**     Abstract  :
**         This component "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
**     Settings  :
**             Timer capture encapsulation : Capture
**
**         Timer
**             Timer                   : ECT_Counter
**             Counter shared          : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**           Maximal time for capture register
**             Xtal ticks              : 1398101
**             microseconds            : 174763
**             milliseconds            : 175
**             seconds (real)          : 0.174762666667
**             Hz                      : 6
**           One tick of timer is
**             microseconds            : 2.666667
**
**         Initialization:
**              Timer                  : Disabled
**              Events                 : Disabled
**
**         Timer registers
**              Capture                : ECT_TC5   [$005A]
**              Counter                : ECT_TCNT  [$0044]
**              Mode                   : ECT_TIOS  [$0040]
**              Run                    : ECT_TSCR1 [$0046]
**              Prescaler              : ECT_TSCR2 [$004D]
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       18            |  PT5_IOC5_VREGAPI
**             ----------------------------------------------------
**
**         Port name                   : T
**         Bit number (in port)        : 5
**         Bit mask of the port        : $0020
**
**         Signal edge/level           : rising
**         Priority                    : 4
**         Pull option                 : off
**
**     Contents  :
**         Enable          - byte AC_CP_IOC_Enable(void);
**         Disable         - byte AC_CP_IOC_Disable(void);
**         EnableEvent     - byte AC_CP_IOC_EnableEvent(void);
**         DisableEvent    - byte AC_CP_IOC_DisableEvent(void);
**         Reset           - byte AC_CP_IOC_Reset(void);
**         GetCaptureValue - byte AC_CP_IOC_GetCaptureValue(AC_CP_IOC_TCapturedValue *Value);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __AC_CP_IOC
#define __AC_CP_IOC

/* MODULE AC_CP_IOC. */

#include "Cpu.h"

#pragma DATA_SEG AC_CP_IOC_DATA        /* Select data segment "AC_CP_IOC_DATA" */
#pragma CODE_SEG AC_CP_IOC_CODE

#define AC_CP_IOC_TCapturedValue word /* Type of the captured value */
#define AC_CP_IOC_PRESCALER_VALUE 0x80U /* Initial prescaler value of the timer */
#define AC_CP_IOC_TIMER_INPUT_CLOCK 0x02DC6C00UL /* DEPRECATED. Initial timer input clock frequency [Hz] */
#define AC_CP_IOC_COUNTER_INPUT_CLOCK_HZ 0x0005B8D8UL /* Initial counter input clock frequency [Hz] */
/* High speed mode constants */
#define AC_CP_IOC_PRESCALER_VALUE_HIGH 0x80U /* Initial prescaler value of the timer in high speed mode */
#define AC_CP_IOC_TIMER_INPUT_CLOCK_HIGH 0x02DC6C00UL /* DEPRECATED. Timer input clock frequency [Hz] in high speed mode */
#define AC_CP_IOC_COUNTER_INPUT_CLOCK_HZ_HIGH 0x0005B8D8UL /* Initial counter input clock frequency [Hz] in high speed mode */

extern volatile bool AC_CP_IOC_EnEvent; /* Enable/Disable events */
extern volatile word AC_CP_IOC_CntrState; /* Content of counter */

byte AC_CP_IOC_Enable(void);
/*
** ===================================================================
**     Method      :  AC_CP_IOC_Enable (component Capture)
**
**     Description :
**         This method enables the component - it starts the capture. Events
**         may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte AC_CP_IOC_Disable(void);
/*
** ===================================================================
**     Method      :  AC_CP_IOC_Disable (component Capture)
**
**     Description :
**         This method disables the component - it stops the capture. No
**         events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define AC_CP_IOC_EnableEvent() \
  (AC_CP_IOC_EnEvent = TRUE , ERR_OK)
/*
** ===================================================================
**     Method      :  AC_CP_IOC_EnableEvent (component Capture)
**
**     Description :
**         This method enables the events. This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define AC_CP_IOC_DisableEvent() (AC_CP_IOC_EnEvent = FALSE , ERR_OK)
/*
** ===================================================================
**     Method      :  AC_CP_IOC_DisableEvent (component Capture)
**
**     Description :
**         This method disables the events.  This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define AC_CP_IOC_Reset() (AC_CP_IOC_CntrState = ECT_TCNT , ERR_OK)
/*
** ===================================================================
**     Method      :  AC_CP_IOC_Reset (component Capture)
**
**     Description :
**         This method resets the counter register (see implementation
**         note in <General Info>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define AC_CP_IOC_GetCaptureValue(Value) \
  /*lint -save  -e926 -e927 -e928 -e929 Disable MISRA rule (11.4) checking. */\
 (((*(AC_CP_IOC_TCapturedValue*)(Value) = ECT_TC5), \
   (*(AC_CP_IOC_TCapturedValue*)(Value) -= AC_CP_IOC_CntrState)), \
  ERR_OK) \
  /*lint -restore Enable MISRA rule (11.4) checking. */
/*
** ===================================================================
**     Method      :  AC_CP_IOC_GetCaptureValue (component Capture)
**
**     Description :
**         This method gets the last value captured by enabled timer.
**         Note: one tick of timer is
**               2.666667 us in high speed mode
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the content of the
**                           capture register
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

void AC_CP_IOC_Init(void);
/*
** ===================================================================
**     Method      :  AC_CP_IOC_Init (component Capture)
**
**     Description :
**         Initializes the associated peripheral(s) and the components 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void AC_CP_IOC_Interrupt(void);
#pragma CODE_SEG AC_CP_IOC_CODE
/*
** ===================================================================
**     Method      :  Interrupt (component Capture)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes of the component event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT

/* END AC_CP_IOC. */

#endif /* ifndef __AC_CP_IOC */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
