/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : MC9S12XEP100_144
**     Version   : Component 01.003, Driver 02.06, CPU db: 3.00.036
**     Datasheet : MC9S12XEP100 Rev. 1.19 12/2008
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/3/30, 15:16
**     Abstract  :
**         This component "MC9S12XEP100_144" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt      - void Cpu_EnableInt(void);
**         DisableInt     - void Cpu_DisableInt(void);
**         SetWaitMode    - void Cpu_SetWaitMode(void);
**         SetStopMode    - void Cpu_SetStopMode(void);
**         Delay100US     - void Cpu_Delay100US(word us100);
**         GetResetSource - byte Cpu_GetResetSource(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "wdi.h"
#include "Timer.h"
#include "CAN0.h"
#include "CAN1.h"
#include "CAN4.h"
#include "CPU_CHG_S.h"
#include "CPU_CHG_P.h"
#include "ISO_CTRL_POS.h"
#include "ISO_CTRL_NEG.h"
#include "ISO_POW.h"
#include "CPUDI1.h"
#include "CPUDI2.h"
#include "CPUDI3.h"
#include "CPUDI4.h"
#include "CPU_SUMV_SDA.h"
#include "CPU_SUMV_SCL.h"
#include "CPU_SUMV_RDY.h"
#include "SUMV_POW.h"
#include "CPU_SUMV_EXT_SDA.h"
#include "CPU_SUMV_EXT_SCL.h"
#include "CPU_ISO_SDA.h"
#include "CPU_ISO_SCL.h"
#include "ExternFlash_Rst.h"
#include "ExternFlash_Cs.h"
#include "ExternFlash_Sck.h"
#include "ExternFlash_Si.h"
#include "ExternFlash_So.h"
#include "CPU_TLE_CO1.h"
#include "ExternTimer_Int.h"
#include "ExternTimer_Scl.h"
#include "ExternTimer_Sda.h"
#include "PORTA0.h"
#include "PORTA1.h"
#include "PORTA2.h"
#include "CON1.h"
#include "Slaver_Pow_Ctrl.h"
#include "CPU_RLY_POS.h"
#include "CPU_RLY_NEG.h"
#include "CPU_RLY_PRE.h"
#include "CPU_RLY_CHG.h"
#include "CPU_RLY_CTRL.h"
#include "RELAY_DIG_ST34.h"
#include "RELAY_DIG_ST12.h"
#include "AI1.h"
#include "AI2.h"
#include "CHG_CAN_POW.h"
#include "CPUCAN_CAR_EN.h"
#include "CPUCAN_INT_EN.h"
#include "CURPOWER.h"
#include "CPUCINT.h"
#include "CPUCSO.h"
#include "CPUCSI.h"
#include "CPUCSCK.h"
#include "CPUCCS.h"
#include "ExtEE_Sck.h"
#include "ExtEE_Sda.h"
#include "CPU_CAR_CAN_STB.h"
#include "CPU_CAR_CAN_ERR.h"
#include "ExtEE_Wp.h"
#include "AC_CP_IOC.h"
#include "RELAY_CHG.h"
#include "RELAY_PRE.h"
#include "RELAY_NEG.h"
#include "RELAY_POS.h"
#include "RELAY_HEAT.h"
#include "RELAY_DIG_ST5.h"
#include "RELAY_FAN.h"
#include "RELAY_DIG_ST6.h"
#include "CPUDO2.h"
#include "CPUDO1.h"
#include "CPU_RLY_HEAT.h"
#include "CPU_RLY_FAN.h"
#include "CPUEE.h"
#include "Timer_1ms.h"
#include "Lock_UnLock.h"
#include "Lock_Lock.h"
#include "LTC_SPI.h"
#include "LTC_CS.h"
#include "Events.h"
#include "TimerEvents.h"
#include "CAN0Events.h"
#include "CAN1Events.h"
#include "CAN4Events.h"
#include "AC_CP_IOCEvents.h"
#include "Cpu.h"

#define CGM_DELAY  0x17FFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
volatile byte LastResetSource;         /* Source of last reset */

/*Definition of global shadow variables*/
byte Shadow_K;
byte Shadow_C;
byte Shadow_H;
byte Shadow_D;
byte Shadow_J;

#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12XEP100_144)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu__WatchDog_EntryPoint (component MC9S12XEP100_144)
**
**     Description :
**         This event is called immediately after fetching of the 
**         WatchDog reset vector, i.e. Processor Expert initialization 
**         and startup initialization have not been done before.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _WatchDog_EntryPoint(void)
{
  setReg8(RTICTL, CPU_WATCHDOG_RESET); /* Remember reset source */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm   jmp _EntryPoint;             /* Jump to regular startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S12XEP100_144)
**
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**                         - The value of zero results in maximal 
**                           delay of approx. 6.5 seconds.
**     Returns     : Nothing
** ===================================================================
*/
#pragma NO_ENTRY                       /* Suppress generation of entry code in a function */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
#pragma MESSAGE DISABLE C5703          /*Disable C5703: Parameter ‘<Parameter>’ declared in function ‘<Function>’ but not referenced */
void Cpu_Delay100US(word us100)
{
  /* irremovable overhead (ignored): 13 cycles */
  /* ldd:  2 cycles overhead (load parameter into register) */
  /* jsr:  4 cycles overhead (call this function) */
  /* rts:  7 cycles overhead (return from this function) */

  /* irremovable overhead for each 100us cycle (counted): 13 cycles */
  /* dbne:  3 cycles overhead (return from this function) */

  /*lint -save  -e950 -e522 Disable MISRA rule (1.1,14.2) checking. */
  asm {
    loop:
    /* 100 us delay block begin */
    /*
     * Delay
     *   - requested                  : 100 us @ 48MHz,
     *   - possible                   : 4800 c, 100000 ns
     *   - without removable overhead : 4797 c, 99937.5 ns
     */
    pshd                               /* (2 c: 41.67 ns) backup D */
    ldd #$063C                         /* (2 c: 41.67 ns) number of iterations */
    label0:
    dbne d, label0                     /* (3 c: 62.5 ns) repeat 1596x */
    puld                               /* (3 c: 62.5 ns) restore D */
    nop                                /* (1 c: 20.83 ns) wait for 1 c */
    nop                                /* (1 c: 20.83 ns) wait for 1 c */
    /* 100 us delay block end */
    dbne d, loop                       /* us100 parameter is passed via D register */
    rts                                /* return from subroutine */
  };
  /*lint -restore Enable MISRA rule (1.1,14.2) checking. */
}

#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12XEP100_144)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12XEP100_144)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12XEP100_144)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12XEP100_144)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_GetResetSource (component MC9S12XEP100_144)
**
**     Description :
**         This method returns soucre of last reset.
**     Parameters  : None
**     Returns     :
**         ---             - One of the following constants is
**                           return by this method
**                           CPU_POWER_ON_RESET             - Last
**                           reset has been caused by Low level
**                           detection at the RESET pin (External
**                           Eeset). 
**                           CPU_WATCHDOG_RESET             - Last
**                           reset has been caused by COP.
**                           CPU_CLOCK_MONITOR_RESET    - Last reset
**                           has been caused by Clock monitor failure.
**                           CPU_LVI_RESET
**                           - Last reset has been caused by Low
**                           voltage detection.
**                           CPU_ILLEGAL_ADDRESS_RESET - Last reset
**                           has been caused by Illegal Address
**                           access.
**                           CPU_EXTERNAL_RESET                - Last
**                           reset has been caused by External reset.
** ===================================================================
*/
byte Cpu_GetResetSource(void)
{
  return(LastResetSource);
}

#pragma OPTION ADD "-Onf"              /* Disable 'Create Sub-Functions with Common Code optimalization' */
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12XEP100_144)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
/* This code is used to initialize global variable, that will contains uniform indenificator of lasty reset source */
  if (RTICTL != 0x00U) {               /* RTICTL register is set to zero after reset. */
    LastResetSource = RTICTL;          /* WatchDog or Clock monitor reset enrty points sets this register to non-zero value */
  } else if (CRGFLG_ILAF == 0x01U) {   /* Illegal Address Reset? */
    LastResetSource = CPU_ILLEGAL_ADDRESS_RESET; /* Store reset reason to the temporary location */
  } else if (CRGFLG_PORF == 0x01U) {   /* Power on Reset? */
    LastResetSource = CPU_POWER_ON_RESET; /* Store reset reason to the temporary location */
  } else if (CRGFLG_LVRF == 0x01U) {   /* Low Voltage Reset? */
    LastResetSource = CPU_LVI_RESET;   /* Store reset reason to the temporary location */
  } else {                             /* (!testReg8Bit(CRGFLG, LVRF)) */
    /* External Reset */
    LastResetSource = CPU_EXTERNAL_RESET; /* Store reset reason to the temporary location */
  }
  /* CRGFLG: RTIF=0,PORF=1,LVRF=1,LOCKIF=0,LOCK=0,ILAF=1,SCMIF=0,SCM=0 */
  setReg8(CRGFLG, 0x64U);              /* Clear POR */ 
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name            Description */
  setReg8(INT_CFADDR, 0x70U);           
  setReg8(INT_CFDATA5, 0x04U);         /*  0x3D  0xFF7A   4   no   ivVpit0         used by PE */ 
  setReg8(INT_CFADDR, 0x90U);           
  setReg8(INT_CFDATA0, 0x04U);         /*  0x48  0xFF90   4   no   ivVcan4tx       used by PE */ 
  setReg8(INT_CFDATA1, 0x04U);         /*  0x49  0xFF92   4   no   ivVcan4rx       used by PE */ 
  setReg8(INT_CFDATA2, 0x04U);         /*  0x4A  0xFF94   4   no   ivVcan4err      used by PE */ 
  setReg8(INT_CFADDR, 0xA0U);           
  setReg8(INT_CFDATA4, 0x04U);         /*  0x54  0xFFA8   4   no   ivVcan1tx       used by PE */ 
  setReg8(INT_CFDATA5, 0x04U);         /*  0x55  0xFFAA   4   no   ivVcan1rx       used by PE */ 
  setReg8(INT_CFDATA6, 0x04U);         /*  0x56  0xFFAC   4   no   ivVcan1err      used by PE */ 
  setReg8(INT_CFADDR, 0xB0U);           
  setReg8(INT_CFDATA0, 0x04U);         /*  0x58  0xFFB0   4   no   ivVcan0tx       used by PE */ 
  setReg8(INT_CFDATA1, 0x04U);         /*  0x59  0xFFB2   4   no   ivVcan0rx       used by PE */ 
  setReg8(INT_CFDATA2, 0x04U);         /*  0x5A  0xFFB4   4   no   ivVcan0err      used by PE */ 
  setReg8(INT_CFADDR, 0xC0U);           
  setReg8(INT_CFDATA5, 0x04U);         /*  0x65  0xFFCA   4   no   ivVectmdcu      used by PE */ 
  setReg8(INT_CFADDR, 0xE0U);           
  setReg8(INT_CFDATA2, 0x04U);         /*  0x72  0xFFE4   4   no   ivVectch5       used by PE */ 
  /* Initialization of Memory Protection unit */
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=1 */
  setReg8(MPUSEL, 0x01U);              /* Select Descriptor num. 1 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=2 */
  setReg8(MPUSEL, 0x02U);              /* Select Descriptor num. 2 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=3 */
  setReg8(MPUSEL, 0x03U);              /* Select Descriptor num. 3 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=4 */
  setReg8(MPUSEL, 0x04U);              /* Select Descriptor num. 4 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=5 */
  setReg8(MPUSEL, 0x05U);              /* Select Descriptor num. 5 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=6 */
  setReg8(MPUSEL, 0x06U);              /* Select Descriptor num. 6 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=7 */
  setReg8(MPUSEL, 0x07U);              /* Select Descriptor num. 7 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=0 */
  setReg8(MPUSEL, 0x00U);              /* Select Descriptor num. 0 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=1,MSTR1=1,MSTR2=1,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0xE0U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* Common initialization of the CPU registers */
  /* PORTB: PB5=0,PB4=0,PB2=0 */
  clrReg8Bits(PORTB, 0x34U);            
  /* PUCR: PUPKE=0,PUPDE=0,PUPCE=0,PUPBE=0,PUPAE=0 */
  clrReg8Bits(PUCR, 0x8FU);             
  /* DDRB: DDRB5=1,DDRB4=1,DDRB2=1 */
  setReg8Bits(DDRB, 0x34U);             
  /* ECT_TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0,??=0,??=0,??=0 */
  setReg8(ECT_TSCR1, 0x00U);            
  /* ECT_MCCTL: MODMC=1,RDMCL=0,MCEN=0,MCPR1=0,MCPR0=1 */
  clrSetReg8Bits(ECT_MCCTL, 0x26U, 0x41U); 
  /* MODRR: MODRR6=0,MODRR3=0,MODRR2=1,MODRR1=0,MODRR0=0 */
  clrSetReg8Bits(MODRR, 0x4BU, 0x04U);  
  /* PORTK: PK7=1,PK6=0,PK5=0,PK4=0,PK3=1,PK2=0,PK1=0,PK0=1 */
  setReg8(PORTK, 0x89U);                
  /* DDRK: DDRK7=1,DDRK6=1,DDRK5=1,DDRK4=1,DDRK3=1,DDRK2=1,DDRK1=1,DDRK0=1 */
  setReg8(DDRK, 0xFFU);                 
  /* PERT: PERT7=0,PERT6=0,PERT5=0,PERT4=0,PERT3=0,PERT2=0,PERT1=0 */
  clrReg8Bits(PERT, 0xFEU);             
  /* PTT: PTT7=0,PTT6=0 */
  clrReg8Bits(PTT, 0xC0U);              
  /* DDRT: DDRT7=1,DDRT6=1,DDRT4=0,DDRT3=0,DDRT2=0,DDRT1=0 */
  clrSetReg8Bits(DDRT, 0x1EU, 0xC0U);   
  /* PIEJ: PIEJ7=0,PIEJ6=0,PIEJ4=0,PIEJ1=0,PIEJ0=0 */
  clrReg8Bits(PIEJ, 0xD3U);             
  /* PERJ: PERJ7=0,PERJ6=0,PERJ4=0,PERJ1=0,PERJ0=0 */
  clrReg8Bits(PERJ, 0xD3U);             
  /* PTJ: PTJ7=0,PTJ6=0,PTJ0=1 */
  clrSetReg8Bits(PTJ, 0xC0U, 0x01U);    
  /* DDRJ: DDRJ7=1,DDRJ6=1,DDRJ4=0,DDRJ3=1,DDRJ1=0,DDRJ0=1 */
  clrSetReg8Bits(DDRJ, 0x12U, 0xC9U);   
  /* PORTC: PC7=0,PC6=0,PC5=0,PC3=1,PC2=0,PC1=0,PC0=0 */
  clrSetReg8Bits(PORTC, 0xE7U, 0x08U);  
  /* DDRC: DDRC7=1,DDRC6=1,DDRC5=1,DDRC3=1,DDRC2=0,DDRC1=1,DDRC0=1 */
  clrSetReg8Bits(DDRC, 0x04U, 0xEBU);   
  /* PIEH: PIEH7=0,PIEH6=0,PIEH5=0,PIEH4=0,PIEH3=0,PIEH2=0,PIEH1=0,PIEH0=0 */
  setReg8(PIEH, 0x00U);                 
  /* PTH: PTH7=0,PTH6=0,PTH5=0,PTH4=0,PTH3=0,PTH2=0,PTH1=0 */
  clrReg8Bits(PTH, 0xFEU);              
  /* PERH: PERH7=0,PERH6=0,PERH5=0,PERH4=0,PERH3=0,PERH2=0,PERH1=0,PERH0=0 */
  setReg8(PERH, 0x00U);                 
  /* DDRH: DDRH7=1,DDRH6=1,DDRH5=1,DDRH4=0,DDRH3=1,DDRH2=1,DDRH1=1,DDRH0=0 */
  setReg8(DDRH, 0xEEU);                 
  /* PORTD: PD5=0,PD4=0,PD3=0,PD2=0 */
  clrReg8Bits(PORTD, 0x3CU);            
  /* DDRD: DDRD7=0,DDRD6=0,DDRD5=1,DDRD4=1,DDRD3=1,DDRD2=1,DDRD1=0,DDRD0=0 */
  setReg8(DDRD, 0x3CU);                 
  /* PORTA: PA7=0,PA6=0,PA5=0,PA4=0,PA3=0 */
  clrReg8Bits(PORTA, 0xF8U);            
  /* DDRA: DDRA7=1,DDRA6=1,DDRA5=1,DDRA4=1,DDRA3=1,DDRA2=0,DDRA1=0,DDRA0=0 */
  setReg8(DDRA, 0xF8U);                 
  /* ATD1DIENL: IEN7=1 */
  setReg8Bits(ATD1DIENL, 0x80U);        
  /* PT1AD1: PT1AD17=1 */
  setReg8Bits(PT1AD1, 0x80U);           
  /* PER1AD1: PER1AD17=0 */
  clrReg8Bits(PER1AD1, 0x80U);          
  /* DDR1AD1: DDR1AD17=1 */
  setReg8Bits(DDR1AD1, 0x80U);          
  /* PTS: PTS7=0,PTS6=0,PTS5=0,PTS2=1,PTS1=1 */
  clrSetReg8Bits(PTS, 0xE0U, 0x06U);    
  /* WOMS: WOMS7=0,WOMS6=0,WOMS5=0,WOMS2=0,WOMS1=0 */
  clrReg8Bits(WOMS, 0xE6U);             
  /* DDRS: DDRS7=1,DDRS6=1,DDRS5=1,DDRS4=0,DDRS3=0,DDRS2=1,DDRS1=1 */
  clrSetReg8Bits(DDRS, 0x18U, 0xE6U);   
  /* PERS: PERS4=0,PERS3=0 */
  clrReg8Bits(PERS, 0x18U);             
  /* ECT_TCTL3: EDG5B=0,EDG5A=0 */
  clrReg8Bits(ECT_TCTL3, 0x0CU);        
  /* ECT_TIE: C5I=0 */
  clrReg8Bits(ECT_TIE, 0x20U);          
  /* ECT_TIOS: IOS5=0 */
  clrReg8Bits(ECT_TIOS, 0x20U);         
  /* ECT_ICOVW: NOVW5=0 */
  clrReg8Bits(ECT_ICOVW, 0x20U);        
  /* ECT_DLYCT: DLY7=0,DLY6=0,DLY5=0,DLY4=0,DLY3=0,DLY2=0,DLY1=0,DLY0=0 */
  setReg8(ECT_DLYCT, 0x00U);            
  /* ECT_ICSYS: SH37=0,SH26=0,SH15=0,SH04=0,TFMOD=0,BUFEN=0,LATQ=0 */
  clrReg8Bits(ECT_ICSYS, 0xFBU);        
  /* ECT_PACTL: CLK1=0,CLK0=0 */
  clrReg8Bits(ECT_PACTL, 0x0CU);        
  /* PIEP: PIEP6=0,PIEP3=0,PIEP2=0,PIEP1=0,PIEP0=0 */
  clrReg8Bits(PIEP, 0x4FU);             
  /* PTP: PTP7=1,PTP6=1,PTP3=0,PTP2=0,PTP1=0,PTP0=0 */
  clrSetReg8Bits(PTP, 0x0FU, 0xC0U);    
  /* PERP: PERP6=0,PERP3=0,PERP2=0,PERP1=0,PERP0=0 */
  clrReg8Bits(PERP, 0x4FU);             
  /* DDRP: DDRP7=1,DDRP6=1,DDRP5=1,DDRP4=0,DDRP3=1,DDRP2=1,DDRP1=1,DDRP0=1 */
  setReg8(DDRP, 0xEFU);                 
  /* PITCFLMT: PITE=0 */
  clrReg8Bits(PITCFLMT, 0x80U);         
  /* PITCE: PCE0=0 */
  clrReg8Bits(PITCE, 0x01U);            
  /* PITTF: PTF0=1 */
  setReg8Bits(PITTF, 0x01U);            
  /* PITMTLD0: PMTLD7=0,PMTLD6=0,PMTLD5=0,PMTLD4=0,PMTLD3=0,PMTLD2=0,PMTLD1=0,PMTLD0=0 */
  setReg8(PITMTLD0, 0x00U);             
  /* PITMUX: PMUX0=0 */
  clrReg8Bits(PITMUX, 0x01U);           
  /* PITINTE: PINTE0=0 */
  clrReg8Bits(PITINTE, 0x01U);          
  /* PTM: PTM7=1,PTM6=1 */
  setReg8Bits(PTM, 0xC0U);              
  /* WOMM: WOMM7=0,WOMM6=0 */
  clrReg8Bits(WOMM, 0xC0U);             
  /* DDRM: DDRM7=1,DDRM6=1 */
  setReg8Bits(DDRM, 0xC0U);             
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 0x12U);           
  /* VREGCTRL: LVIE=0 */
  clrReg8Bits(VREGCTRL, 0x02U);         
  /* COPCTL: WCOP=0,RSBCK=0,WRTMASK=1,??=0,??=0,CR2=0,CR1=0,CR0=0 */
  setReg8(COPCTL, 0x20U);               
  /* DDR0AD1: DDR0AD17=1,DDR0AD16=1,DDR0AD15=1,DDR0AD14=1,DDR0AD13=1,DDR0AD12=1,DDR0AD11=1,DDR0AD10=1 */
  setReg8(DDR0AD1, 0xFFU);              
  /* DDRF: DDRF7=1,DDRF6=1,DDRF5=1,DDRF4=1,DDRF3=1,DDRF2=1,DDRF1=1,DDRF0=1 */
  setReg8(DDRF, 0xFFU);                 
  /* DDRL: DDRL7=1,DDRL6=1,DDRL5=1,DDRL4=1,DDRL3=1,DDRL2=1,DDRL1=1,DDRL0=1 */
  setReg8(DDRL, 0xFFU);                 
  /* DDRR: DDRR7=1,DDRR6=1,DDRR5=1,DDRR4=1,DDRR3=1,DDRR2=1,DDRR1=1,DDRR0=1 */
  setReg8(DDRR, 0xFFU);                 
  /* RDRIV: RDPK=0,RDPE=0,RDPD=0,RDPC=0,RDPB=0,RDPA=0 */
  clrReg8Bits(RDRIV, 0x9FU);            
  /* RDR1AD1: RDR1AD17=0,RDR1AD16=0,RDR1AD15=0,RDR1AD14=0,RDR1AD13=0,RDR1AD12=0,RDR1AD11=0,RDR1AD10=0 */
  setReg8(RDR1AD1, 0x00U);              
  /* RDRH: RDRH7=0,RDRH6=0,RDRH5=0,RDRH4=0,RDRH3=0,RDRH2=0,RDRH1=0,RDRH0=0 */
  setReg8(RDRH, 0x00U);                 
  /* RDRJ: RDRJ7=0,RDRJ6=0,RDRJ5=0,RDRJ4=0,RDRJ2=0,RDRJ1=0,RDRJ0=0 */
  clrReg8Bits(RDRJ, 0xF7U);             
  /* RDRM: RDRM7=0,RDRM6=0,RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  setReg8(RDRM, 0x00U);                 
  /* RDRP: RDRP7=0,RDRP6=0,RDRP5=0,RDRP4=0,RDRP3=0,RDRP2=0,RDRP1=0,RDRP0=0 */
  setReg8(RDRP, 0x00U);                 
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=0,RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  setReg8(RDRS, 0x00U);                 
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0,RDRT3=0,RDRT2=0,RDRT1=0,RDRT0=0 */
  setReg8(RDRT, 0x00U);                 
  /* RDR0AD0: RDR0AD07=0,RDR0AD06=0,RDR0AD05=0,RDR0AD04=0,RDR0AD03=0,RDR0AD02=0,RDR0AD01=0,RDR0AD00=0 */
  setReg8(RDR0AD0, 0x00U);              
  /* RDR1AD0: RDR1AD07=0,RDR1AD06=0,RDR1AD05=0,RDR1AD04=0,RDR1AD03=0,RDR1AD02=0,RDR1AD01=0,RDR1AD00=0 */
  setReg8(RDR1AD0, 0x00U);              
  /* IRQCR: IRQEN=0 */
  clrReg8Bits(IRQCR, 0x40U);            
  /* ATD0DIEN: IEN15=0,IEN14=0,IEN13=0,IEN12=0,IEN11=0,IEN10=0,IEN9=0,IEN8=0,IEN7=0,IEN6=0,IEN5=0,IEN4=0,IEN3=0,IEN2=0,IEN1=0,IEN0=0 */
  setReg16(ATD0DIEN, 0x00U);            
  /* ATD1DIEN: IEN5=0,IEN4=0,IEN3=0,IEN1=0,IEN0=0 */
  clrReg16Bits(ATD1DIEN, 0x3BU);        
  /* ### MC9S12XEP100_144 "Cpu" init code ... */
  /* ### BitIO "wdi" init code ... */
  /* ### TimerInt "Timer" init code ... */
  /* ###  "CAN0" init code ... */
  //CAN0_Init();
  /* ###  "CAN1" init code ... */
  CAN1_Init();
  /* ###  "CAN4" init code ... */
  CAN4_Init();
  /* ### BitIO "CPU_CHG_S" init code ... */
  /* ### BitIO "CPU_CHG_P" init code ... */
  /* ### BitIO "ISO_CTRL_POS" init code ... */
  /* ### BitIO "ISO_CTRL_NEG" init code ... */
  /* ### BitIO "ISO_POW" init code ... */
  /* ### BitIO "CPUDI1" init code ... */
  /* ### BitIO "CPUDI2" init code ... */
  /* ### BitIO "CPUDI3" init code ... */
  /* ### BitIO "CPUDI4" init code ... */
  /* ### BitIO "CPU_SUMV_SDA" init code ... */
  Shadow_K &= 0xDFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "CPU_SUMV_SCL" init code ... */
  /* ### BitIO "CPU_SUMV_RDY" init code ... */
  /* ### BitIO "SUMV_POW" init code ... */
  /* ### BitIO "CPU_SUMV_EXT_SDA" init code ... */
  Shadow_C &= 0xFEU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "CPU_SUMV_EXT_SCL" init code ... */
  /* ### BitIO "CPU_ISO_SDA" init code ... */
  Shadow_C &= 0xFBU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "CPU_ISO_SCL" init code ... */
  /* ### BitIO "ExternFlash_Rst" init code ... */
  Shadow_C &= 0x7FU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_Cs" init code ... */
  Shadow_H &= 0x7FU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_Sck" init code ... */
  Shadow_H &= 0xBFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_Si" init code ... */
  Shadow_H &= 0xDFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_So" init code ... */
  Shadow_H &= 0xEFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "CPU_TLE_CO1" init code ... */
  /* ### BitIO "ExternTimer_Int" init code ... */
  /* ### BitIO "ExternTimer_Scl" init code ... */
  Shadow_D &= 0xFBU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternTimer_Sda" init code ... */
  Shadow_D &= 0xF7U;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "PORTA0" init code ... */
  /* ### BitIO "PORTA1" init code ... */
  /* ### BitIO "PORTA2" init code ... */
  /* ### BitIO "CON1" init code ... */
  /* ### BitIO "Slaver_Pow_Ctrl" init code ... */
  /* ### BitIO "CPU_RLY_POS" init code ... */
  /* ### BitIO "CPU_RLY_NEG" init code ... */
  /* ### BitIO "CPU_RLY_PRE" init code ... */
  /* ### BitIO "CPU_RLY_CHG" init code ... */
  /* ### BitIO "CPU_RLY_CTRL" init code ... */
  /* ### BitIO "RELAY_DIG_ST34" init code ... */
  /* ### BitIO "RELAY_DIG_ST12" init code ... */
  /* ###  "AI1" init code ... */
  AI1_Init();
  /* ###  "AI2" init code ... */
  AI2_Init();
  /* ### BitIO "CHG_CAN_POW" init code ... */
  /* ### BitIO "CPUCAN_CAR_EN" init code ... */
  /* ### BitIO "CPUCAN_INT_EN" init code ... */
  /* ### BitIO "CURPOWER" init code ... */
  /* ### BitIO "CPUCINT" init code ... */
  /* ### BitIO "CPUCSO" init code ... */
  /* ### BitIO "CPUCSI" init code ... */
  /* ### BitIO "CPUCSCK" init code ... */
  /* ### BitIO "CPUCCS" init code ... */
  /* ### BitIO "ExtEE_Sck" init code ... */
  /* ### BitIO "ExtEE_Sda" init code ... */
  Shadow_J &= 0xBFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "CPU_CAR_CAN_STB" init code ... */
  /* ### BitIO "CPU_CAR_CAN_ERR" init code ... */
  /* ### BitIO "ExtEE_Wp" init code ... */
  Shadow_K |= (byte)0x80U;             /* Initialize pin shadow variable bit */
  /* ### Timer capture encapsulation "AC_CP_IOC" init code ... */
  AC_CP_IOC_Init();
  /* ### BitIO "RELAY_CHG" init code ... */
  /* ### BitIO "RELAY_PRE" init code ... */
  /* ### BitIO "RELAY_NEG" init code ... */
  /* ### BitIO "RELAY_POS" init code ... */
  /* ### BitIO "RELAY_HEAT" init code ... */
  /* ### BitIO "RELAY_DIG_ST5" init code ... */
  /* ### BitIO "RELAY_FAN" init code ... */
  /* ### BitIO "RELAY_DIG_ST6" init code ... */
  /* ### BitIO "CPUDO2" init code ... */
  /* ### BitIO "CPUDO1" init code ... */
  /* ### BitIO "CPU_RLY_HEAT" init code ... */
  /* ### BitIO "CPU_RLY_FAN" init code ... */
  /* ### IntEEPROM "CPUEE" init code ... */
  CPUEE_Init();
  /* ### TimerInt "Timer_1ms" init code ... */
  
  /* PITINTE: PINTE0=1 */
  setReg8Bits(PITINTE, 0x01U);          
  /* PITLD0: PLD15=1,PLD14=0,PLD13=1,PLD12=1,PLD11=1,PLD10=0,PLD9=1,PLD8=1,PLD7=1,PLD6=0,PLD5=0,PLD4=0,PLD3=0,PLD2=0,PLD1=0,PLD0=0 */
  setReg16(PITLD0, 0xBB80U);           /* Store given value to the compare register */ 
  /* ### BitIO "Lock_UnLock" init code ... */
  /* ### BitIO "Lock_Lock" init code ... */
  /* ###  Synchro master "LTC_SPI" init code ... */
  LTC_SPI_Init();
  /* ### BitIO "LTC_CS" init code ... */
  /* Common peripheral initialization - ENABLE */
  /* ECT_TSCR1: TEN=1,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0,??=0,??=0,??=0 */
  setReg8(ECT_TSCR1, 0x80U);            
  /* PITCFLMT: PITE=1 */
  setReg8Bits(PITCFLMT, 0x80U);         
  __DI();                              /* Disable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

#pragma CODE_SEG __NEAR_SEG NON_BANKED

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12XEP100_144)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab of the CPU component. !!! ***/


#pragma OPTION ADD "-Onf"              /* 'Create Sub-Functions with Common Code optimalization' must be disabled because stack is not yet initialized */

#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{

  /*** !!! Here you can place your own code using property "User code before PE initialization" on the build options tab of the CPU compoennt. !!! ***/

  /* ### MC9S12XEP100_144 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* MMCCTL1: TGMRAMON=0,??=0,EEEIFRON=0,PGMIFRON=0,RAMHM=0,EROMON=0,ROMHM=0,ROMON=1 */
  setReg8(MMCCTL1, 0x01U);              
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  setReg8(DIRECT, 0x00U);               
  /* ECLKCTL: NECLK=1,NCLKX2=1,DIV16=0,EDIV4=0,EDIV3=0,EDIV2=0,EDIV1=0,EDIV0=0 */
  setReg8(ECLKCTL, 0xC0U);              
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,XCLKS=0,??=0,PLLWAI=0,??=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0x00U);              /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0x81U);              /* Disable the PLL */ 
  /* SYNR: VCOFRQ1=1,VCOFRQ0=1,SYNDIV5=0,SYNDIV4=0,SYNDIV3=0,SYNDIV2=1,SYNDIV1=0,SYNDIV0=1 */
  setReg8(SYNR, 0xC5U);                /* Set the multiplier register */ 
  /* REFDV: REFFRQ1=1,REFFRQ0=0,REFDIV5=0,REFDIV4=0,REFDIV3=0,REFDIV2=0,REFDIV1=0,REFDIV0=0 */
  setReg8(REFDV, 0x80U);               /* Set the divider register */ 
  /* POSTDIV: ??=0,??=0,??=0,POSTDIV4=0,POSTDIV3=0,POSTDIV2=0,POSTDIV1=0,POSTDIV0=0 */
  setReg8(POSTDIV, 0x00U);             /* Set the post divider register */ 
  /* PLLCTL: CME=1,PLLON=1,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xC1U);               
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 0x80U);          /* Select clock source from PLL */ 
  /* VREGHTCL: ??=0,??=0,VSEL=0,VAE=1,HTEN=0,HTDS=0,HTIE=0,HTIF=0 */
  setReg8(VREGHTCL, 0x10U);             
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code using property "User code after PE initialization" on the build options tab of the CPU component. !!! ***/

  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
