/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CPU_SUMV_EXT_SDA.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/3/23, 21:47
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       28            |  PC0_DATA8
**             ----------------------------------------------------
**
**         Port name                   : C
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTC     [$0004]
**         Port control register       : DDRC      [$0006]
**
**         Optimization for            : speed
**     Contents  :
**         SetDir - void CPU_SUMV_EXT_SDA_SetDir(bool Dir);
**         GetVal - bool CPU_SUMV_EXT_SDA_GetVal(void);
**         PutVal - void CPU_SUMV_EXT_SDA_PutVal(bool Val);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE CPU_SUMV_EXT_SDA. */

#include "CPU_SUMV_EXT_SDA.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG CPU_SUMV_EXT_SDA_DATA /* Select data segment "CPU_SUMV_EXT_SDA_DATA" */
#pragma CODE_SEG CPU_SUMV_EXT_SDA_CODE
#pragma CONST_SEG CPU_SUMV_EXT_SDA_CONST /* Constant section for this module */
/*
** ===================================================================
**     Method      :  CPU_SUMV_EXT_SDA_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool CPU_SUMV_EXT_SDA_GetVal(void)

**  This method is implemented as a macro. See CPU_SUMV_EXT_SDA.h file.  **
*/

/*
** ===================================================================
**     Method      :  CPU_SUMV_EXT_SDA_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void CPU_SUMV_EXT_SDA_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PORTC, 0x01U);         /* PC0=0x01U */
    Shadow_C |= 0x01U;                 /* Set-up shadow variable */
  } else { /* !Val */
    clrReg8Bits(PORTC, 0x01U);         /* PC0=0x00U */
    Shadow_C &= 0xFEU;                 /* Set-up shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  CPU_SUMV_EXT_SDA_SetDir (component BitIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void CPU_SUMV_EXT_SDA_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PORTC, (getReg8(PORTC) & (byte)(~(byte)0x01U)) | (Shadow_C & 0x01U)); /* PC0=Shadow_C[bit 0] */
    setReg8Bits(DDRC, 0x01U);          /* DDRC0=0x01U */
  } else { /* !Dir */
    clrReg8Bits(DDRC, 0x01U);          /* DDRC0=0x00U */
  } /* !Dir */
}


/* END CPU_SUMV_EXT_SDA. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
