/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CPUCAN_CAR_EN.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/3/23, 21:47
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       34            |  PB2_ADDR2_IVD2
**             ----------------------------------------------------
**
**         Port name                   : B
**
**         Bit number (in port)        : 2
**         Bit mask of the port        : $0004
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTB     [$0001]
**         Port control register       : DDRB      [$0003]
**
**         Optimization for            : speed
**     Contents  :
**         PutVal - void CPUCAN_CAR_EN_PutVal(bool Val);
**         ClrVal - void CPUCAN_CAR_EN_ClrVal(void);
**         SetVal - void CPUCAN_CAR_EN_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE CPUCAN_CAR_EN. */

#include "CPUCAN_CAR_EN.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG CPUCAN_CAR_EN_DATA    /* Select data segment "CPUCAN_CAR_EN_DATA" */
#pragma CODE_SEG CPUCAN_CAR_EN_CODE
#pragma CONST_SEG CPUCAN_CAR_EN_CONST  /* Constant section for this module */
/*
** ===================================================================
**     Method      :  CPUCAN_CAR_EN_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void CPUCAN_CAR_EN_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PORTB, 0x04U);         /* PB2=0x01U */
  } else { /* !Val */
    clrReg8Bits(PORTB, 0x04U);         /* PB2=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  CPUCAN_CAR_EN_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void CPUCAN_CAR_EN_ClrVal(void)

**  This method is implemented as a macro. See CPUCAN_CAR_EN.h file.  **
*/

/*
** ===================================================================
**     Method      :  CPUCAN_CAR_EN_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void CPUCAN_CAR_EN_SetVal(void)

**  This method is implemented as a macro. See CPUCAN_CAR_EN.h file.  **
*/


/* END CPUCAN_CAR_EN. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
