/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ExtEE_Wp.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/3/23, 21:47
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       140           |  PK7_ROMCTL_EWAIT
**             ----------------------------------------------------
**
**         Port name                   : K
**
**         Bit number (in port)        : 7
**         Bit mask of the port        : $0080
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : off
**
**         Port data register          : PORTK     [$0032]
**         Port control register       : DDRK      [$0033]
**
**         Optimization for            : speed
**     Contents  :
**         SetInput  - void ExtEE_Wp_SetInput(void);
**         SetOutput - void ExtEE_Wp_SetOutput(void);
**         GetVal    - bool ExtEE_Wp_GetVal(void);
**         ClrVal    - void ExtEE_Wp_ClrVal(void);
**         SetVal    - void ExtEE_Wp_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE ExtEE_Wp. */

#include "ExtEE_Wp.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG ExtEE_Wp_DATA         /* Select data segment "ExtEE_Wp_DATA" */
#pragma CODE_SEG ExtEE_Wp_CODE
#pragma CONST_SEG ExtEE_Wp_CONST       /* Constant section for this module */
/*
** ===================================================================
**     Method      :  ExtEE_Wp_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool ExtEE_Wp_GetVal(void)

**  This method is implemented as a macro. See ExtEE_Wp.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExtEE_Wp_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ExtEE_Wp_ClrVal(void)

**  This method is implemented as a macro. See ExtEE_Wp.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExtEE_Wp_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ExtEE_Wp_SetVal(void)

**  This method is implemented as a macro. See ExtEE_Wp.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExtEE_Wp_SetInput (component BitIO)
**
**     Description :
**         This method sets direction of the component to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ExtEE_Wp_SetInput(void)

**  This method is implemented as a macro. See ExtEE_Wp.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExtEE_Wp_SetOutput (component BitIO)
**
**     Description :
**         This method sets direction of the component to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ExtEE_Wp_SetOutput(void)
{
  setReg8(PORTK, (getReg8(PORTK) & (byte)(~(byte)0x80U)) | (Shadow_K & 0x80U)); /* PK7=Shadow_K[bit 7] */
  setReg8Bits(DDRK, 0x80U);            /* DDRK7=0x01U */
}


/* END ExtEE_Wp. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
