/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ExtEE_Sck.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/3/23, 21:47
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       128           |  PJ7_KWJ7_TxCAN4_SCL0_TxCAN0
**             ----------------------------------------------------
**
**         Port name                   : J
**
**         Bit number (in port)        : 7
**         Bit mask of the port        : $0080
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTJ       [$0268]
**         Port control register       : DDRJ      [$026A]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool ExtEE_Sck_GetVal(void);
**         ClrVal - void ExtEE_Sck_ClrVal(void);
**         SetVal - void ExtEE_Sck_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE ExtEE_Sck. */

#include "ExtEE_Sck.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG ExtEE_Sck_DATA        /* Select data segment "ExtEE_Sck_DATA" */
#pragma CODE_SEG ExtEE_Sck_CODE
#pragma CONST_SEG ExtEE_Sck_CONST      /* Constant section for this module */
/*
** ===================================================================
**     Method      :  ExtEE_Sck_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool ExtEE_Sck_GetVal(void)

**  This method is implemented as a macro. See ExtEE_Sck.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExtEE_Sck_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ExtEE_Sck_ClrVal(void)

**  This method is implemented as a macro. See ExtEE_Sck.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExtEE_Sck_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ExtEE_Sck_SetVal(void)

**  This method is implemented as a macro. See ExtEE_Sck.h file.  **
*/


/* END ExtEE_Sck. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
