/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ExternTimer_Sda.h
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/3/23, 21:47
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       68            |  PD3_DATA3
**             ----------------------------------------------------
**
**         Port name                   : D
**
**         Bit number (in port)        : 3
**         Bit mask of the port        : $0008
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTD     [$0005]
**         Port control register       : DDRD      [$0007]
**
**         Optimization for            : speed
**     Contents  :
**         SetInput  - void ExternTimer_Sda_SetInput(void);
**         SetOutput - void ExternTimer_Sda_SetOutput(void);
**         GetVal    - bool ExternTimer_Sda_GetVal(void);
**         ClrVal    - void ExternTimer_Sda_ClrVal(void);
**         SetVal    - void ExternTimer_Sda_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef ExternTimer_Sda_H_
#define ExternTimer_Sda_H_

/* MODULE ExternTimer_Sda. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG ExternTimer_Sda_CODE
/*
** ===================================================================
**     Method      :  ExternTimer_Sda_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define ExternTimer_Sda_GetVal() ( \
    (bool)((getReg8(PORTD) & 0x08U))   /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  ExternTimer_Sda_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define ExternTimer_Sda_ClrVal() ( \
    (void)clrReg8Bits(PORTD, 0x08U)    /* PD3=0x00U */, \
    (Shadow_D &= 0xF7U)                /* Set appropriate bit in shadow variable */ \
  )

/*
** ===================================================================
**     Method      :  ExternTimer_Sda_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define ExternTimer_Sda_SetVal() ( \
    (void)setReg8Bits(PORTD, 0x08U)    /* PD3=0x01U */, \
    (Shadow_D |= 0x08U)                /* Set appropriate bit in shadow variable */ \
  )

/*
** ===================================================================
**     Method      :  ExternTimer_Sda_SetInput (component BitIO)
**
**     Description :
**         This method sets direction of the component to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define ExternTimer_Sda_SetInput() ( \
    (void)clrReg8Bits(DDRD, 0x08U)     /* DDRD3=0x00U */ \
  )

/*
** ===================================================================
**     Method      :  ExternTimer_Sda_SetOutput (component BitIO)
**
**     Description :
**         This method sets direction of the component to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ExternTimer_Sda_SetOutput(void);

#pragma CODE_SEG DEFAULT

/* END ExternTimer_Sda. */
#endif /* #ifndef __ExternTimer_Sda_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
