// ErrorMacro.h
#ifndef ERRORMACRO_H
#define ERRORMACRO_H


#include "Ecu.h"
#include "SchIf.h"


// macro define should be adjusted for different projects
// you could define new macro if new project needs
#define ERROR_TM_MS(ms)  ((ms) / 20) // ms must can be divided by 10

#define ERR_CNT_SET_SUMV_HIGH_L1         (ERROR_TM_MS(10000))
#define ERR_CNT_SET_SUMV_HIGH_L2         (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SUMV_HIGH_L3         (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SUMV_HIGH_L1         (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SUMV_HIGH_L2         (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SUMV_HIGH_L3         (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SUMV_HIGH_L1    (0) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_HIGH_L2    (0) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_HIGH_L3    (0) // 0.1V

#define ERR_CNT_SET_SUMV_LOW_L1         (ERROR_TM_MS(10000))
#define ERR_CNT_SET_SUMV_LOW_L2         (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SUMV_LOW_L3         (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_SUMV_LOW_L1         (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SUMV_LOW_L2         (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SUMV_LOW_L3         (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SUMV_LOW_L1    (0) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_LOW_L2    (0) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_LOW_L3    (0) // 0.1V

#define ERR_CNT_SET_TEMPER_HIGH_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_TEMPER_HIGH_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_TEMPER_HIGH_L3       (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_TEMPER_HIGH_L1       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_TEMPER_HIGH_L2       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_TEMPER_HIGH_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L1  (0) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L2  (0) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L3  (0) // 1'C

#define ERR_CNT_SET_TEMPER_LOW_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_TEMPER_LOW_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_TEMPER_LOW_L3       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_TEMPER_LOW_L1       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_TEMPER_LOW_L2       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_TEMPER_LOW_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L1  (0) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L2  (0) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L3  (0) // 1'C

#define ERR_CNT_SET_DELTT_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_DELTT_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_DELTT_L3        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_DELTT_L1        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_DELTT_L2        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_DELTT_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_DELTT_L1   (0) // 1'C
#define ERR_THRHD_HYSTRS_DELTT_L2   (0) // 1'C
#define ERR_THRHD_HYSTRS_DELTT_L3   (0) // 1'C

#define ERR_CNT_SET_DELTV_L1        (ERROR_TM_MS(3000))
#define ERR_CNT_SET_DELTV_L2        (ERROR_TM_MS(3000))
#define ERR_CNT_SET_DELTV_L3        (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_DELTV_L1        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_DELTV_L2        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_DELTV_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_DELTV_L1   (0) // 1mv
#define ERR_THRHD_HYSTRS_DELTV_L2   (0) // 1mv
#define ERR_THRHD_HYSTRS_DELTV_L3   (0) // 1mv

#define ERR_CNT_SET_CELLV_HIGH_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_HIGH_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_HIGH_L3        (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_CELLV_HIGH_L1        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_HIGH_L2        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_HIGH_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L1   (0) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L2   (0) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L3   (0) // 1mv

#define ERR_CNT_SET_CELLV_LOW_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_LOW_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_LOW_L3        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_LOW_L1        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_LOW_L2        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_LOW_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CELLV_LOW_L1   (0) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_LOW_L2   (0) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_LOW_L3   (0) // 1mv

#define ERR_CNT_SET_CURCHG_L1       (ERROR_TM_MS(10000))
#define ERR_CNT_SET_CURCHG_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURCHG_L3       (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_CURCHG_L1       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURCHG_L2       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURCHG_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURCHG_L1  (0) // 0.1A
#define ERR_THRHD_HYSTRS_CURCHG_L2  (0) // 0.1A
#define ERR_THRHD_HYSTRS_CURCHG_L3  (0) // 0.1A

#define ERR_CNT_SET_CURDCH_L1       (ERROR_TM_MS(10000))
#define ERR_CNT_SET_CURDCH_L2       (ERROR_TM_MS(30000))
#define ERR_CNT_SET_CURDCH_L3       (ERROR_TM_MS(15000))
#define ERR_CNT_CLR_CURDCH_L1       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURDCH_L2       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURDCH_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURDCH_L1  (0) // 0.1A
#define ERR_THRHD_HYSTRS_CURDCH_L2  (0) // 0.1A
#define ERR_THRHD_HYSTRS_CURDCH_L3  (0) // 0.1A

#define ERR_CNT_SET_CURFEEDBAK_L1       (ERROR_TM_MS(10000))
#define ERR_CNT_SET_CURFEEDBAK_L2       (ERROR_TM_MS(20000))
#define ERR_CNT_SET_CURFEEDBAK_L3       (ERROR_TM_MS(10000))
#define ERR_CNT_CLR_CURFEEDBAK_L1       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURFEEDBAK_L2       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURFEEDBAK_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURFEEDBAK_L1  (0) // 0.1A
#define ERR_THRHD_HYSTRS_CURFEEDBAK_L2  (0) // 0.1A
#define ERR_THRHD_HYSTRS_CURFEEDBAK_L3  (0) // 0.1A

#define ERR_CNT_SET_SOC_HIGH_L1          (ERROR_TM_MS(3000))
#define ERR_CNT_SET_SOC_HIGH_L2          (ERROR_TM_MS(2000))
#define ERR_CNT_SET_SOC_HIGH_L3          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_HIGH_L1          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_HIGH_L2          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_HIGH_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOC_HIGH_L1     (0) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_HIGH_L2     (0) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_HIGH_L3     (0) // 0.1%

#define ERR_CNT_SET_SOC_LOW_L1          (ERROR_TM_MS(3000))
#define ERR_CNT_SET_SOC_LOW_L2          (ERROR_TM_MS(3000))
#define ERR_CNT_SET_SOC_LOW_L3          (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_SOC_LOW_L1          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_LOW_L2          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_LOW_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOC_LOW_L1     (0) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_LOW_L2     (0) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_LOW_L3     (0) // 0.1%

#define ERR_CNT_SET_INTRES_L1       (ERROR_TM_MS(2000))
#define ERR_CNT_SET_INTRES_L2       (ERROR_TM_MS(2000))
#define ERR_CNT_SET_INTRES_L3       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_INTRES_L1       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_INTRES_L2       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_INTRES_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_INTRES_L1  (0) // 0.1mO
#define ERR_THRHD_HYSTRS_INTRES_L2  (0) // 0.1mO
#define ERR_THRHD_HYSTRS_INTRES_L3  (0) // 0.1mO

#define ERR_CNT_SET_TPOLE_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TPOLE_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TPOLE_L3        (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_TPOLE_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TPOLE_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TPOLE_L3        (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_TPOLE_L1   (0) // 1'C
#define ERR_THRHD_HYSTRS_TPOLE_L2   (0) // 1'C
#define ERR_THRHD_HYSTRS_TPOLE_L3   (0) // 1'C

#define ERR_CNT_SET_SOH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOH_L3          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOH_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOH_L1     (0) // 0.1%
#define ERR_THRHD_HYSTRS_SOH_L2     (0) // 0.1%
#define ERR_THRHD_HYSTRS_SOH_L3     (0) // 0.1%

#define ERR_CNT_SET_POWVOLT_HIGH_L1      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_HIGH_L2      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_HIGH_L3      (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_POWVOLT_HIGH_L1      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_HIGH_L2      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_HIGH_L3      (ERROR_TM_MS(1000))
#define ERR_THRHD_HYSTRS_POWVOLT_HIGH_L1 (0) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_HIGH_L2 (0) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_HIGH_L3 (0) // 0.5v

#define ERR_CNT_SET_POWVOLT_LOW_L1      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_LOW_L2      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_LOW_L3      (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_POWVOLT_LOW_L1      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_LOW_L2      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_LOW_L3      (ERROR_TM_MS(1000))
#define ERR_THRHD_HYSTRS_POWVOLT_LOW_L1 (0) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_LOW_L2 (0) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_LOW_L3 (0) // 0.5v

#define ERR_THRHD_POWVOLT_HIGH_L1   (300) // 30V
#define ERR_THRHD_POWVOLT_HIGH_L2   (310) // 31V
#define ERR_THRHD_POWVOLT_HIGH_L3   (320) // 32V

#define ERR_THRHD_POWVOLT_LOW_L1    (0)  // 0.1V
#define ERR_THRHD_POWVOLT_LOW_L2    (0)  // 0.1V
#define ERR_THRHD_POWVOLT_LOW_L3    (0)  // 0.1V

//#define ERR_CHG_CUR_TABLE
//#define ERR_DIS_CUR_TABLE
//#define ERR_FDB_CUR_TABLE

#define ERR_CHG_CUR_GAIN_L1  10
#define ERR_CHG_CUR_GAIN_L2  12
#define ERR_CHG_CUR_GAIN_L3  15

#define ERR_DIS_CUR_GAIN_L1  10
#define ERR_DIS_CUR_GAIN_L2  12
#define ERR_DIS_CUR_GAIN_L3  15

#define ERR_FDB_CUR_GAIN_L1  10
#define ERR_FDB_CUR_GAIN_L2  12
#define ERR_FDB_CUR_GAIN_L3  15

#define ERR_CNT_CAN4_L1       (ERROR_TM_MS(5000)) 
#define ERR_CLR_CAN4_L1_EN  1              // 1: can clear err_code bit, 0:hold 
#define ERR_CNT_CAN4_L2       (ERROR_TM_MS(5000))
#define ERR_CLR_CAN4_L2_EN  1 
#define ERR_CNT_CAN4_L3       (ERROR_TM_MS(5000))
#define ERR_CLR_CAN4_L3_EN  1   

#endif /* ERRORMACRO_H */